-- ============================================================
-- IMUNE - Health Investment Advisor
-- Dashboard Geral
-- ============================================================

-- 1. Atendimentos por hospital
SELECT
    AP_NOME_HOSPITAL AS LABEL,
    COUNT(*) AS VALUE
FROM ADMIN.BARI
WHERE (:P2_HOSPITAL IS NULL OR AP_NOME_HOSPITAL = :P2_HOSPITAL)
GROUP BY AP_NOME_HOSPITAL
ORDER BY VALUE DESC;


-- 2. Atendimentos ao longo do tempo
SELECT
    TO_CHAR(TRUNC(AP_DTSOLIC, 'MM'),'MON/YYYY','NLS_DATE_LANGUAGE=PORTUGUESE') AS MES, COUNT(*) AS TOTAL, TRUNC(AP_DTSOLIC, 'MM') AS ORDEM_MES
FROM ADMIN.BARI
WHERE AP_DTSOLIC IS NOT NULL
  AND (:P2_HOSPITAL IS NULL OR AP_NOME_HOSPITAL = :P2_HOSPITAL)
GROUP BY TRUNC(AP_DTSOLIC, 'MM')
ORDER BY ORDEM_MES;


-- 3. Tempo médio de autorização por hospital
SELECT
    AP_NOME_HOSPITAL AS HOSPITAL,
    ROUND(AVG(AP_DTAUT - AP_DTSOLIC), 1) AS DIAS
FROM ADMIN.BARI
WHERE AP_DTAUT IS NOT NULL
  AND AP_DTSOLIC IS NOT NULL
GROUP BY AP_NOME_HOSPITAL
HAVING AVG(AP_DTAUT - AP_DTSOLIC) > 0
ORDER BY DIAS DESC;